#!/usr/bin/env sh
export PATH="$HOME/scripts:$HOME/.cabal/bin:$PATH"
export LC_TIME="C"
export LC_NUMERIC="C"

export MOZ_USE_XINPUT2=1

export GTK_IM_MODULE=ibus
export QT_IM_MODULE=ibus
export XMODIFIERS=@im=ibus

# setxkbmap c98
# xkbcomp ~/dot/c98.xkb $DISPLAY
xset -dpms s off
compton --config ~/dot/compton.conf -b &
ibus-daemon &
# xkbset nullify lock &

