from .separator import Separator
from .clock import Clock
from .battery import Battery
from .temperature import Temperature
from .wifi import Wifi
from .ram import RAM
from .cpugraph import CPUGraph
from .volume_alsa import AlsaVolume
from .ibus import IBus
from .disk import Disk
from .pacman import Pacman
