#!/usr/bin/env python3
import os
import re
import sys

n = int(sys.argv[1])

def gt(name):
	match = re.fullmatch(r".*?(\d+).*\..*", name) # type: re.match
	if not match:
		return False
	return int(match.groups()[0]) >= n

eps = list(filter(gt, sorted(os.listdir())))

os.execvp("baka-mplayer", ["baka-mplayer"] + eps)
