#!/usr/bin/env python3
import sys
import re
import subprocess
import dmenu

keys = []
chars = {}
with open(sys.argv[1], "rt") as file:
	for line in file:
		line = line.rstrip('\n').split("#", 1)[0].strip()
		if not line:
			continue
		v, k = line.split(" ")
		k += " " + chr(int(v, 16))
		keys.append(k)
		chars[k] = chr(int(v, 16))

code = dmenu.show(keys)

if code is not None:
	numRe = re.compile("#([0-9]+)")
	hexRe = re.compile("#x([0-9a-fA-F]+)")

	char = None
	if code in chars:
		char = chars[code]
	elif hexRe.match(code):
		char = chr(int(hexRe.match(code).group(1), 16))
	elif numRe.match(code):
		char = chr(int(numRe.match(code).group(1)))

	if char:
		subprocess.Popen(["xtype", char])
