#!/usr/bin/env python3
import dmenu
import xtype
import os.path

def parse(path):
	chars = {}
	for line in open(path).read().splitlines():
		line = line.split("#", 1)[0].rstrip()
		if not line:
			continue
		assert len(line) > 2
		assert line[1] == "\t"
		char = line[0]
		key = " ".join(line[2:].split())
		chars[char + " " + key] = char
	return chars

chars = parse(os.path.expanduser("~/dot/compose.txt"))
code = dmenu.show(chars)

if code is not None:
	char = None
	if code[:1] == "#":
		char = chr(int(code[1:], 16))
	elif code in chars:
		char = chars[code]

	if char:
		xtype.xtype([xtype.get_char(char)])
