#!/usr/bin/env python3
import sys
import argparse

p = argparse.ArgumentParser()
p.add_argument("num", nargs="+")
args = p.parse_args()

a = []
for arg in args.num:
	try: a.append("%X" % int(arg))
	except Exception: pass
print(*a)
