#!/bin/zsh

if [[ $BLOCK_BUTTON == 1 ]]; then
	i3-sensible-terminal --disable-factory --command "sudo apt-get upgrade"
else
	read upg new rem not < <(apt-get --dry-run upgrade | grep -m1 '^[0-9]\+ upgraded,' | grep -o '[0-9]\+' | tr '\n' ' ')
fi


if (( upg+new+rem+not > 0 )); then
	echo "Updates!"
	echo "Updates!"
	echo "#FF7F7F"
else
	echo "No updates"
	echo "No updates"
	echo ""
fi
