#!/bin/zsh

read a b state percent time < <(acpi -b)

state=${state%,}
percent=${${percent%,}[1,-2]}
time=${time[1,5]}

out=()
out+="$percent%"
[[ $state == "Discharging" ]] && out+=("DIS" "($time)")
[[ $state == "Charging" ]] && out+=("CHR" "($time)")

color=""
case $((percent / 20)) in
	0)   color="#FF0000";;
	1)   color="#FF7F00";;
	2)   color="#FFFF00";;
	3)   color="#00FF00";;
	4|5) color="#FFFFFF";;
esac

echo $out
echo $out
echo $color
