#!/bin/zsh

#$sink: sink index
#$2: action (inc, dec, mute, get)
#$3: possibly "i3". If it is, do some I3-related stuff,
#    like sending sig10 or using i3blocks format

sink=1

case $1 in
	inc|dec|mute)
		case $1 in
			inc)  pactl set-sink-volume $sink -- +5% ;;
			dec)  pactl set-sink-volume $sink -- -5% ;;
			mute) pactl set-sink-mute   $sink toggle ;;
		esac
		pkill -RTMIN+10 i3blocks
	;;
	get)
		read muted vol < <(pactl list sinks | sed -rn '
			/^Sink #'$sink'$/,/^Sink #/{
				/^\tMute: /{
					s/^\tMute: +(yes|no)$/\1/
					p
				}
				/^\tVolume: /{
					s/^\tVolume: +0: +([0-9]+)% +1: +[0-9]+%/\1/
					p
				}
			}' | tr "\n" " ")
		echo $vol%
		echo $vol%

		r=255
		g=255
		b=255
		if [[ $muted == "yes" ]]; then
			let r=r/2
			let g=g/2
			let b=b/2
		fi
		if [[ vol -gt 100 ]]; then
			let g=g/2
			let b=b/2
		fi

		printf "#%02X%02X%02X\n" $r $g $b
	;;
esac
