#!/usr/bin/env zsh

[[ -z $1 ]] && echo "No argument" && exit 1
(($1)) && pid=$1 || pid=$(pgrep "$1" | head -n1)
[[ -z $pid ]] && echo "Process not found" && exit 1
cd "/proc/$pid/cwd"
cmd="$(cat /proc/$pid/cmdline)"
cmda=("${(0@)cmd}")

kill $pid
$cmda >/dev/null 2>&1 &
