#!/usr/bin/env python3
import argparse
import sys
import re
import ly.document
import ly.rhythm
import ly.pitch.rel2abs
import ly.pitch.abs2rel
import ly.pitch.transpose
import ly.reformat
import ly.indent

argp = argparse.ArgumentParser()
sp = argp.add_subparsers(dest="command", required=True)

p = sp.add_parser("double")
def double(c): ly.rhythm.rhythm_double(c)

p = sp.add_parser("halve")
def halve(c): ly.rhythm.rhythm_halve(c)

p = sp.add_parser("implicit")
p.add_argument("per_line", action="store_true")
def implicit(c, per_line): (ly.rhythm.rhythm_implicit_per_line if per_line else ly.rhythm.rhythm_implicit)(c)

p = sp.add_parser("explicit")
def explicit(c): ly.rhythm.rhythm_explicit(c)

p = sp.add_parser("relative")
def relative(c): ly.pitch.abs2rel.abs2rel(c, startpitch=True, first_pitch_absolute=True)

p = sp.add_parser("absolute")
def absolute(c): ly.pitch.rel2abs.rel2abs(c, first_pitch_absolute=True)

p = sp.add_parser("transpose")
p.add_argument("fr", nargs="?")
p.add_argument("to")
def transpose(c, *, fr="c", to):
	def parsePitch(p):
		name, oct = re.fullmatch(r"([a-z]+)([,']*)", p).groups()
		return ly.pitch.Pitch(*ly.pitch.pitchReader("nederlands")(name), ly.pitch.octaveToNum(oct))
	transposer = ly.pitch.transpose.Transposer(parsePitch(fr), parsePitch(to))
	ly.pitch.transpose.transpose(c, transposer, relative_first_pitch_absolute=True)

p = sp.add_parser("format")
def format(c):
	with c.document as d:
		lines = set()
		for b in d:
			firstNonWhite, lastNonWhite = None, None
			for t in b.tokens:
				pos = b.position + t.pos
				end = b.position + t.end

				if isinstance(t, ly.lex.Space):
					if pos in lines:
						del d[pos:end]
						lines.remove(pos)
						lines.add(end)
				else:
					if firstNonWhite is None:
						firstNonWhite = pos
				lastNonWhite = end

				if isinstance(t, ly.lex.lilypond.PipeSymbol):
					lines.add(end)
				if isinstance(t, ly.lex.Indent):
					lines.add(end)
				if isinstance(t, ly.lex.Dedent):
					lines.add(pos)

			if firstNonWhite in lines:
				lines.remove(firstNonWhite)
			if lastNonWhite in lines:
				lines.remove(lastNonWhite)

		for l in lines:
			d[l:l] = "\n"
	ly.indent.Indenter().indent(c)
	ly.reformat.remove_trailing_whitespace(c)

del sp
del p

def __main__():
	args = vars(argp.parse_args())
	command = args.pop("command")

	doc = ly.document.Document(sys.stdin.read())
	cursor = ly.document.Cursor(doc)
	globals()[command](cursor, **{ k: v for k, v in args.items() if v is not None })
	print(doc.plaintext(), end="")

if __name__ == "__main__":
	__main__()
