#!/bin/zsh
i3-msg append_layout =(echo '{
	"layout": "tabbed",
	"percent": 0.1,
	"nodes": [{
		"name": "Videos",
		"swallows": [{
			"class": "^Totem$",
			"instance": "^totem$"
		}]
	}]
} {
	"percent": 0.17,
	"name": "RuneScape",
	"swallows": [{
		"class": "^Runescape$",
		"title": "^RuneScape$"
	}]
}')

optirun runescape-launcher
