#!/usr/bin/env sh
dir="$1"
[[ -z "$dir" ]] && dir="sandbox"
[[ -d "$dir" ]] || {
	echo "'$dir' is not a directory"
	exit 1
}

tmp="$(mktemp -d)"
unionfs -o cow "$dir"=RW:"$HOME" "$tmp"
export HOME="$tmp"
export C98_SANDBOX="$tmp"
cd "$HOME"
"$SHELL" -i
fusermount -uz "$tmp"
rmdir "$tmp"
