#!/usr/bin/env python3
import subprocess
from pathlib import Path

mimes = set()
mimes |= set(subprocess.check_output(["lsdesktopf", "--gm", "0"]).decode().splitlines())
mimes |= set("x-scheme-handler/" + f[29:] for f in subprocess.check_output(["gconftool-2", "--all-dirs", "/desktop/gnome/url-handlers"]).decode().splitlines())
mimes.add("x-scheme-handler/file")
mimes = sorted(mimes)

# Mimeapps
Path("~/.local/share/applications/xdg-open.desktop").expanduser().write_text("""
[Desktop Entry]
Type=Application
Name=xdg-open
Exec=/usr/bin/env xdg-open %u
NoDisplay=true
MimeType={};
""".format(";".join(mimes)).strip())
with Path("~/.config/mimeapps.list").expanduser().open("w") as f:
	f.write("[Default Applications]\n")
	for mime in mimes:
		f.write("%s=xdg-open.desktop\n" % mime)

# Gconf
subprocess.check_output(["gconftool-2", "--recursive-unset", "/desktop/gnome/url-handlers"])
for mime in mimes:
	type, sub = mime.split("/")
	if type != "x-scheme-handler":
		continue
	def gconf(t, k, v):
		subprocess.check_output(["gconftool-2", "--type", t, "--set", "/desktop/gnome/url-handlers/%s/%s" % (sub, k), v])
	gconf("str", "command", "xdg-open %s")
	gconf("bool", "enabled", "true")
	gconf("bool", "needs_terminal", "false")
