#!/usr/bin/env python3
import os
import argparse
import subprocess

argp = argparse.ArgumentParser()
argp.add_argument("file")
args = argp.parse_args()

f = args.file # type: str

if f.startswith("file://"):
	f = f[7:]
if ":" in f:
	type, sub = "x-scheme-handler", f.split(":")[0]
else:
	f = os.path.realpath(f)
	type, sub = subprocess.check_output(["mimetype", "--output-format", "%m", f]).decode().strip().split("/", 2)
	desc = subprocess.check_output(["mimetype", "--output-format", "%d", f]).decode().strip()

env = os.environ

run = {}
def register(*cmd):
	def _(*mimes):
		for m in mimes:
			run[m] = cmd
	return _

register("x-terminal-emulator", "-x", env["EDITOR"], f)("text/*", "inode/x-empty", "application/xml", "application/javascript", "application/x-shellscript")
register(env["BROWSER"], f)("text/html", "application/pdf", "image/svg", "x-scheme-handler/http", "x-scheme-handler/https")
register("gimp", f)("image/*")
register("baka-mplayer", f)("video/*")
register("musescore", f)("application/x-musescore", "audio/midi")
register("x-terminal-emulator", "--working-directory", f)("inode/directory")
register("engrampa", f)("application/zip", "application/x-rar", "application/vnd.rar", "application/x-java-archive", "application/x-7z-compressed", "application/x-compressed-tar", "application/x-bzip-compressed-tar", "application/x-bzip")
register("deluge", f)("application/x-bittorrent", "x-scheme-handler/magnet")
register("loffice", f)("application/vnd.openxmlformats-officedocument.wordprocessingml.document", "application/vnd.openxmlformats-officedocument.presentationml.presentation")

cmd = run.get("%s/%s" % (type, sub)) or run.get("%s/*" % type)
if not cmd:
	cmd = ["notify-send", "Don't know how to handle '%s/%s' (%s) file" % (type, sub, desc), f]
print("%s/%s:" % (type, sub), " ".join(map(repr, cmd)))

os.execvp(cmd[0], cmd)
