#!/usr/bin/env python3
import os
import magic
import argparse
from fnmatch import fnmatch

argp = argparse.ArgumentParser()
argp.add_argument("file")
args = argp.parse_args()

f = args.file # type: str

if f.startswith("file://"):
	f = f[7:]
if ":" in f:
	type, sub = "protocol", f.split(":")[0]
else:
	if not os.path.exists(f):
		argp.error("%s: no such file or directory" % f)
	if os.path.isdir(f):
		type, sub = "inode", "directory"
	else:
		type, sub = magic.from_file(f, mime=True).split("/", 2)

if (type, sub) == ("application", "zip") and fnmatch(f, "*.mscz"):
	sub = "mscore"

env = os.environ

run = {}
run["text/*"] = ["x-terminal-emulator", "-x", env["EDITOR"], f]
run["text/html"] = [env["BROWSER"], f]
run["image/*"] = ["gimp", f]
run["video/*"] = ["baka-mplayer", f]
run["audio/midi"] = ["musescore", f]
run["inode/directory"] = ["x-terminal-emulator", "--working-directory", f]
run["application/zip"] = ["engrampa", f]
run["application/x-rar"] = ["engrampa", f]
run["application/x-bittorrent"] = ["deluge", f]

run["inode/x-empty"] = run["text/*"]
run["application/pdf"] = run["text/html"]
run["application/mscore"] = run["audio/midi"]
run["image/svg"] = run["text/html"]

run["protocol/http"] = run["text/html"]
run["protocol/https"] = run["text/html"]
run["protocol/magnet"] = run["application/x-bittorrent"]

cmd = run.get("%s/%s" % (type, sub)) or run.get("%s/*" % type)
if not cmd:
	cmd = ["notify-send", "Don't know how to handle '%s/%s' file" % (type, sub), f]
print("%s/%s:" % (type, sub), " ".join(map(repr, cmd)))
if not os.fork():
	os.execvp(cmd[0], cmd)
