#!/usr/bin/env python3

import time
import sys
import Xlib.X
import Xlib.display
KEYCODE = 255

display = Xlib.display.Display()
for char in map(ord, " ".join(sys.argv[1:]) or input()):
	keysym = char | 0x01000000
	if 0x80 <= char <= 0xFF: #the 0x01000000 trick doesn't work for 80..FF, for whatever reason
		keysym &= 0xFFFFFF
	display.change_keyboard_mapping(KEYCODE, [(keysym,)*8])
	display.xtest_fake_input(Xlib.X.KeyPress, KEYCODE)
	display.xtest_fake_input(Xlib.X.KeyRelease, KEYCODE)
	display.sync()
	time.sleep(1/10)
