[tool.poetry]
name = "icebar"
version = "1.0.0"
description = "An i3bar lookalike, unburdened by the limitations of text"
authors = ["Kyuuhachi <caagr98@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.7,<4"
PyGObject = "^3.40.1"
appdirs = "^1.4.4"
anyio = "^3.2.1"
psutil = "^5.8.0"
xlib = "^0.21"

[tool.poetry.scripts]
icebar = "icebar.bar:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
