#{{{1 History
setopt histignorealldups sharehistory
HISTSIZE=1000
SAVEHIST=1000
HISTFILE=~/.zsh_history

#{{{1 Utils
autoload -Uz compinit && compinit
autoload -Uz colors && colors
autoload -U zmv

trim() {
	awk '
	{
		len = 0
		out = ""
		for(i = 1; i <= length($0) && len < '$1'; i++) {
			ch = substr($0, i, 1)
			if(ch == "\x1b") {
				end = index(substr($0, i), "m")
				if(end > 0) {
					out = out substr($0, i, end)
					i += end - 1
				}
			} else {
				out = out ch
				len++
			}
		}
		print out
	}
	'
}

#{{{1 Variables
win=/media/caagr98/OSDisk/Users/admusr
: ~win
s=car0b1nius@muncher.se
alias su="sudo $SHELL"

#{{{1 CNF
command_not_found_handler() {
	python /usr/lib/command-not-found $1
	exit 127
}

#{{{1 Color
#{{{2 Man
export LESS_TERMCAP_mb=$(printf "$fg[red]")
export LESS_TERMCAP_md=$(printf "$fg[blue]")
export LESS_TERMCAP_us=$(printf "$fg[green]")
export LESS_TERMCAP_so=$(printf "")
export LESS_TERMCAP_me=$(printf "$reset_color")
export LESS_TERMCAP_se=$(printf "$reset_color")
export LESS_TERMCAP_ue=$(printf "$reset_color")

#{{{2 Maven
mvn() {
	=mvn $@ | sed \
		-e "s/^\[INFO]/${fg[blue]}${bold_color}[INFO]${reset_color}/" \
		-e "s/^\[WARNING]/${fg[yellow]}${bold_color}[WARNING]${reset_color}/" \
		-e "s/^\[ERROR]/${fg[red]}${bold_color}[ERROR]${reset_color}/"
}

#{{{2 ls
ls() {
	if [[ -t 1 ]]; then
		=ls -F -x --color --group-directories-first $@
	else
		=ls -F $@
	fi
}
#{{{1 Ctrl-Z
ctrlz() {
	[[ $(jobs | wc -l) > 0 ]] && zle push-line && BUFFER="fg" && zle accept-line
}
zle -N ctrlz
bindkey "^Z" ctrlz

#{{{1 Syntax highlight
source ~/dot/zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets)

typeset -A ZSH_HIGHLIGHT_STYLES
ZSH_HIGHLIGHT_STYLES[alias]='fg=magenta,bold'
ZSH_HIGHLIGHT_STYLES[path]='fg=cyan'
ZSH_HIGHLIGHT_STYLES[single-hyphen-option]='fg=blue'
ZSH_HIGHLIGHT_STYLES[double-hyphen-option]='fg=blue'

#{{{1 Complete (I have no idea what this stuff means)
source ~/dot/zsh/zsh-completions/zsh-completions.plugin.zsh
unsetopt menu_complete   # do not autoselect the first completion entry
unsetopt flowcontrol
setopt auto_menu         # show completion menu on succesive tab press
setopt complete_in_word
setopt always_to_end
WORDCHARS=''
zmodload -i zsh/complist
eval "$(dircolors -b)"

#{{{2
zstyle ':completion:*' auto-description 'specify: %d'
zstyle ':completion:*' completer _expand _complete _correct _approximate
zstyle ':completion:*' format 'Completing %d'
zstyle ':completion:*' group-name ''
zstyle ':completion:*' menu select=2
zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*' list-colors ''
zstyle ':completion:*' list-prompt %SAt %p: Hit TAB for more, or the character to insert%s
zstyle ':completion:*' matcher-list '' 'm:{a-z}={A-Z}' 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=* l:|=*'
zstyle ':completion:*' menu select=long
zstyle ':completion:*' select-prompt %SScrolling active: current selection at %p%s
zstyle ':completion:*' use-compctl false
zstyle ':completion:*' verbose true

zstyle ':completion:*:*:kill:*:processes' list-colors '=(#b) #([0-9]#)*=0=01;31'
zstyle ':completion:*:kill:*' command 'ps -u $USER -o pid,%cpu,tty,cputime,cmd'

zstyle ':completion:*' matcher-list 'm:{A-Za-z}={a-zA-Z}'

#{{{2
zstyle ':completion:*' matcher-list 'm:{a-zA-Z-_}={A-Za-z_-}' 'r:|[._-]=* r:|=*' 'l:|=* r:|=*'
# zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=*' 'l:|=* r:|=*'

zstyle ':completion:*' list-colors ''
zstyle ':completion:*:*:*:*:*' menu select
zstyle ':completion:*:*:kill:*:processes' list-colors '=(#b) #([0-9]#) ([0-9a-z-]#)*=01;34=0=01'
zstyle ':completion:*:*:*:*:processes' command "ps -u $USER -o pid,user,comm -w -w"

# disable named-directories autocompletion
zstyle ':completion:*:cd:*' tag-order local-directories directory-stack path-directories

# Use caching so that commands like apt and dpkg complete are useable
zstyle ':completion::complete:*' use-cache 1
zstyle ':completion::complete:*' cache-path $ZSH_CACHE_DIR

# Don't complete uninteresting users
zstyle ':completion:*:*:*:users' ignored-patterns \
	adm amanda apache at avahi avahi-autoipd beaglidx bin cacti canna \
	clamav daemon dbus distcache dnsmasq dovecot fax ftp games gdm \
	gkrellmd gopher hacluster haldaemon halt hsqldb ident junkbust kdm \
	ldap lp mail mailman mailnull man messagebus  mldonkey mysql nagios \
	named netdump news nfsnobody nobody nscd ntp nut nx obsrun openvpn \
	operator pcap polkitd postfix postgres privoxy pulse pvm quagga radvd \
	rpc rpcuser rpm rtkit scard shutdown squid sshd statd svn sync tftp \
	usbmux uucp vcsa wwwrun xfs '_*'

# ... unless we really want to.
zstyle '*' single-ignored show

expand-or-complete-with-dots() {
	# toggle line-wrapping off and back on again
	[[ -n "$terminfo[rmam]" && -n "$terminfo[smam]" ]] && echoti rmam
	print -Pn "%{%F{red}......%f%}"
	[[ -n "$terminfo[rmam]" && -n "$terminfo[smam]" ]] && echoti smam

	zle expand-or-complete
	zle redisplay
}
zle -N expand-or-complete-with-dots
bindkey "^I" expand-or-complete-with-dots

#{{{1 Prompt
source ~/dot/zsh/prompt.zsh
